databases:
  - name: budget
    databaseName: budget
    user: budget
    plan: free

services:
  - type: web
    name: budget
    runtime: ruby
    plan: free
    buildCommand: "bundle install"
    # preDeployCommand: "bin/rails assets:precompile" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default